### ISSUE TITLE
Stuck at "Waiting for media to load.." and nothing happens

### ISSUE THREAD

**Issue by gt0203** [gamethrower/Robogram#2]
Hello,

Thank you for sharing!

I have a problem:
when I launch the script with the command 'python robogram.py' it tells me:

Scraper launched.
Downloading insta2post recent posts..
Image downloaded successfully.
Finished downloading insta2post recent posts.
Quitting scraper..
Found cookies. Injecting..
Cookies injected. Scheduling media..
Waiting for media to load..

and I'm stuck here and nothing happens.

Thanks in advance.

**Comment by gt0203** [comment]
Ok i have found the solution it's my fault.

But i have 1 more question : Can i change the interval between posts (hours) in to minutes ?

**Comment by gamethrower** [comment]
> But i have 1 more question : Can i change the interval between posts (hours) in to minutes ?

Nope 😬
